### PR TITLE
V3 to master. Do not merge, please.

### PR DESCRIPTION
**Pull request by featalion**
Rebased version of v3 client library.

### CODE REVIEW

**Comment by featalion** [comment]
@sunloverz could you please test this version. Thanks!

**Comment by sunloverz** [comment]
https://github.com/iron-io/iron_mq_python/pull/40

**Comment by sunloverz** [comment]
Everything works fine except alerts, can't remote alerts, but it is backend issue

**Comment by featalion** [comment]
Seems, need to move `featalion:v3 -> iron_mq_python:v3` first ( :

**Comment by featalion** [comment]
Will be reopened from current repository's v3 branch to master.

**Pull request closed without merging**
